name: Integration Test
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: Run integration test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: [3.8, 3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run Tests
        run: bash tests/integration_test.sh
      - name: Clean up
        if: always()
        run: |
          echo "Cleaning up test data"
          rm -rf config
          rm -rf data
